### ISSUE TITLE
about the tau in traing process

### ISSUE THREAD

**Issue by wisdomGEsLA** [junkangwu/Adap_tau#1]
Thanks for the excellent work by the authors. I'm confused about the values of tau when I run the code by:

_bash Adap_tau_novel.sh amazon-book 1e-3 1e-7 3 1024 2048 nopdrop 1.0 1.0 uniform_gpu 0 100 cosine mf weight_mean_

here's an example in a epoch:

2023-05-05 16:20:39,454 - [INFO] - current w_0 is 9.65932889229748
2023-05-05 16:22:47,693 - [INFO] - E:6|_**TAU:7.724 17.2**_, train_time: 126.4, VALID_time: 1.813, loss: 3.757e+03, emb_loss:1.48e-05, best_valid(recall@20): 0.04892
valid 	 N@10: 0.03014, R@10: 0.02926, P@10: 0.02303
valid 	 N@20: 0.03826, R@20: 0.04941, P@20: 0.01996
valid 	 N@50: 0.05434, R@50: 0.09246, P@50: 0.01561

I know they are the min and max of tau,  Are they the tau used in SSM loss? If so, I'm wondering why the values are so large since the common range of tau is [0,1].

**Comment by junkangwu** [comment]
Apologies for the delayed response. Last week, I attended the WWW2023 conference in Austin. 
The printed value signifies 1/tau, while the tau utilized falls within the normal range of [0,1].

Best,
junkang
